### ISSUE TITLE
bork

### ISSUE THREAD

**Issue by NotSoSuper** [Leystryku/steamavatarchange#3]
https://i.mods.nyc/s/AgVuAPhNoxGZRGz
After 1-2 Minutes of it trying, either the method is broken or I'm doing something wrong/

I checked the post request when actually uploading the file to steam from the browser and it seems as I'm putting the right info.

**Comment by Codingale** [comment]
You need the new format probably eg:

`"76561198035758390||Numbers"`
in the steamLogin cookie.

**Comment by GarnettGaming** [comment]
Codingale what if you don't find it, I can't find it....
